# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def common()
    use_frameworks!
    pod 're', :path => '../'
end

abstract_target 'AllPods' do
    common()
    
    target 'Sample' do
    end
end

